// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core__Array from "@rescript/core/src/Core__Array.res.mjs";
import * as JjUtilsJs from "../lib/jjUtils.js";

function buildChangeGraph(prim) {
  return JjUtilsJs.buildChangeGraph();
}

async function analyzeCommand() {
  console.log("Building change graph from user bookmarks...");
  var changeGraph = await JjUtilsJs.buildChangeGraph();
  console.log("\n=== CHANGE GRAPH RESULTS ===");
  console.log("Total bookmarks: " + String(changeGraph.bookmarks.length));
  console.log("Total stacks: " + String(changeGraph.stacks.length));
  if (changeGraph.stacks.length > 0) {
    console.log("\n=== BOOKMARK STACKS ===");
    changeGraph.stacks.forEach(function (stack, i) {
          console.log("\nStack " + String(i + 1 | 0) + ":");
          console.log("  Bookmarks: " + stack.segments.flatMap(function (s) {
                      return s.bookmarks.map(function (b) {
                                  return b.name;
                                });
                    }).join(", "));
          var totalChanges = Core__Array.reduce(stack.segments, 0, (function (sum, segment) {
                  return sum + segment.changes.length | 0;
                }));
          console.log("  Total changes: " + String(totalChanges));
          if (stack.segments.length > 1) {
            console.log("  📚 This is a stacked set of bookmarks!");
            return ;
          }
          
        });
  }
  console.log("\n=== INDIVIDUAL BOOKMARK DETAILS ===");
  changeGraph.segmentChanges.forEach(function (segmentChanges, bookmarkName) {
        console.log("\n" + bookmarkName + ":");
        console.log("  Segment changes: " + String(segmentChanges.length));
        var match = segmentChanges.at(0);
        var match$1 = Core__Array.last(segmentChanges);
        if (match !== undefined && match$1 !== undefined) {
          console.log("  Latest: " + match.descriptionFirstLine);
          console.log("  Oldest: " + match$1.descriptionFirstLine);
          return ;
        }
        
      });
}

export {
  buildChangeGraph ,
  analyzeCommand ,
}
/* ../lib/jjUtils.js Not a pure module */
