// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$Ink from "ink";
import * as React from "react";
import * as Process from "process";
import * as JsxRuntime from "react/jsx-runtime";

var $$Text = {};

function AnalyzeCommandComponent(props) {
  var prStatusMap = props.prStatusMap;
  var isDataActionable = Array.from(props.changeGraph.bookmarks.values()).some(function (bookmark) {
        if (!bookmark.hasRemote || !bookmark.isSynced) {
          return true;
        } else {
          return prStatusMap.get(bookmark.name) === undefined;
        }
      });
  React.useEffect((function () {
          if (!isDataActionable) {
            Process.exit(0);
          }
          
        }), []);
  return JsxRuntime.jsx($$Ink.Text, {
              children: "isDataActionable: " + String(isDataActionable)
            });
}

var make = AnalyzeCommandComponent;

export {
  $$Text ,
  make ,
}
/* ink Not a pure module */
