// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$Ink from "ink";
import * as Js_exn from "rescript/lib/es6/js_exn.js";
import * as Core__Array from "@rescript/core/src/Core__Array.res.mjs";
import * as Core__Option from "@rescript/core/src/Core__Option.res.mjs";
import * as SubmitJs from "../lib/submit.js";
import * as JjUtilsJs from "../lib/jjUtils.js";
import * as JsxRuntime from "react/jsx-runtime";
import * as Caml_js_exceptions from "rescript/lib/es6/caml_js_exceptions.js";
import * as AnalyzeCommandComponent from "./AnalyzeCommandComponent.res.mjs";

function buildChangeGraph(prim) {
  return JjUtilsJs.buildChangeGraph();
}

function gitFetch(prim) {
  return JjUtilsJs.gitFetch();
}

function getExistingPRs(prim0, prim1, prim2, prim3) {
  return SubmitJs.getExistingPRs(prim0, prim1, prim2, prim3);
}

function getGitHubConfig(prim) {
  return SubmitJs.getGitHubConfig();
}

async function analyzeCommand() {
  console.log("Fetching from remote...");
  try {
    await JjUtilsJs.gitFetch();
  }
  catch (raw_error){
    var error = Caml_js_exceptions.internalToOCamlException(raw_error);
    if (error.RE_EXN_ID === Js_exn.$$Error) {
      console.error("Error fetching from remote: " + Core__Option.getOr(error._1.message, "Unknown error"));
    } else {
      throw error;
    }
  }
  console.log("Building change graph from user bookmarks...");
  var changeGraph = await JjUtilsJs.buildChangeGraph();
  var prStatusMap;
  try {
    console.log("Getting GitHub configuration...");
    var githubConfig = await SubmitJs.getGitHubConfig();
    console.log("Fetching existing pull requests...");
    prStatusMap = await getExistingPRs(githubConfig.octokit, githubConfig.owner, githubConfig.repo, changeGraph.bookmarks.map(function (b) {
              return b.name;
            }));
  }
  catch (raw_error$1){
    var error$1 = Caml_js_exceptions.internalToOCamlException(raw_error$1);
    if (error$1.RE_EXN_ID === Js_exn.$$Error) {
      console.error("Error getting GitHub PRs: " + Core__Option.getOr(error$1._1.message, "Unknown error"));
      prStatusMap = new Map();
    } else {
      throw error$1;
    }
  }
  $$Ink.render(JsxRuntime.jsx(AnalyzeCommandComponent.make, {
            changeGraph: changeGraph,
            prStatusMap: prStatusMap
          }));
  console.log("\n=== CHANGE GRAPH RESULTS ===");
  console.log("Total bookmarks: " + String(changeGraph.bookmarks.length));
  console.log("Total stacks: " + String(changeGraph.stacks.length));
  if (changeGraph.stacks.length > 0) {
    console.log("\n=== BOOKMARK STACKS ===");
    changeGraph.stacks.forEach(function (stack, i) {
          console.log("\nStack " + String(i + 1 | 0) + ":");
          console.log("  Bookmarks: " + stack.segments.flatMap(function (s) {
                      return s.bookmarks.map(function (b) {
                                  return b.name;
                                });
                    }).join(", "));
          var totalChanges = Core__Array.reduce(stack.segments, 0, (function (sum, segment) {
                  return sum + segment.changes.length | 0;
                }));
          console.log("  Total changes: " + String(totalChanges));
          if (stack.segments.length > 1) {
            console.log("  📚 This is a stacked set of bookmarks!");
            return ;
          }
          
        });
  }
  console.log("\n=== INDIVIDUAL BOOKMARK DETAILS ===");
  changeGraph.segmentChanges.forEach(function (segmentChanges, bookmarkName) {
        console.log("\n" + bookmarkName + ":");
        console.log("  Segment changes: " + String(segmentChanges.length));
        var match = segmentChanges.at(0);
        var match$1 = Core__Array.last(segmentChanges);
        if (match !== undefined && match$1 !== undefined) {
          console.log("  Latest: " + match.descriptionFirstLine);
          console.log("  Oldest: " + match$1.descriptionFirstLine);
          return ;
        }
        
      });
}

export {
  buildChangeGraph ,
  gitFetch ,
  getExistingPRs ,
  getGitHubConfig ,
  analyzeCommand ,
}
/* ink Not a pure module */
