// Generated by ReScript, PLEASE EDIT WITH CARE

import * as AuthJs from "../lib/auth.js";

function getGitHubAuth(prim) {
  return AuthJs.getGitHubAuth();
}

function getAuthDetails(prim) {
  return AuthJs.getAuthDetails(prim);
}

function sourceToString(source) {
  if (source === "gh-cli") {
    return "GitHub CLI";
  } else {
    return "Environment Variable";
  }
}

async function authTestCommand() {
  console.log("🔐 Testing GitHub Authentication...\n");
  var authConfig = await AuthJs.getGitHubAuth();
  console.log("✅ Successfully authenticated via: " + sourceToString(authConfig.source));
  var authDetails = await AuthJs.getAuthDetails(authConfig);
  var name = authDetails.name;
  var nameStr = name !== undefined ? name : "No name set";
  console.log("👤 Authenticated as: " + authDetails.username + " (" + nameStr + ")");
  var email = authDetails.email;
  var emailStr = email !== undefined ? email : "Not public";
  console.log("📧 Email: " + emailStr);
  var scopesStr = authDetails.scopes.length > 0 ? authDetails.scopes.join(", ") : "None detected";
  console.log("📋 Token scopes: " + scopesStr);
  if (authDetails.scopes.includes("repo")) {
    console.log("✅ Token has repo access (required for creating PRs)");
  } else {
    console.log("⚠️  Token may not have sufficient permissions for creating PRs");
  }
}

function authHelpCommand() {
  console.log("🔐 GitHub Authentication Help\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\njj-stack supports the following authentication methods (in priority order):\n\n1. 🛠️  GitHub CLI (recommended)\n   Install: https://cli.github.com/\n   Setup: gh auth login\n\n2. 🌍 Environment Variables\n   export GITHUB_TOKEN=your_token_here\n   export GH_TOKEN=your_token_here  # Alternative name\n   \n   Create a Personal Access Token at: https://github.com/settings/tokens/new\n   Required scopes: repo, pull_requests\n\nCommands:\n  jj-stack auth test - Test current authentication\n  jj-stack auth help - Show this help\n\nNote: jj-stack no longer stores tokens locally for security reasons.\nUse GitHub CLI or environment variables for authentication.\n");
}

export {
  getGitHubAuth ,
  getAuthDetails ,
  sourceToString ,
  authTestCommand ,
  authHelpCommand ,
}
/* ../lib/auth.js Not a pure module */
