// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$Ink from "ink";
import * as React from "react";
import * as JsxRuntime from "react/jsx-runtime";

var $$Text = {};

function Counter(props) {
  var match = React.useState(function () {
        return 0;
      });
  var setCounter = match[1];
  var counter = match[0];
  React.useEffect((function () {
          var timer = setInterval((function () {
                  setCounter(function (counter) {
                        return counter + 1 | 0;
                      });
                }), 100);
          return (function () {
                    clearInterval(timer);
                  });
        }), [counter]);
  return JsxRuntime.jsx($$Ink.Text, {
              children: String(counter)
            });
}

var make = Counter;

export {
  $$Text ,
  make ,
}
/* ink Not a pure module */
