// Generated by ReScript, PLEASE EDIT WITH CARE


function sleep(ms) {
  return new Promise((function (resolve, param) {
                setTimeout((function () {
                        resolve();
                      }), ms);
              }));
}

export {
  sleep ,
}
/* No side effect */
