// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JjUtilsJs from "./jjUtils.js";

function getLogOutput(prim) {
  return JjUtilsJs.getLogOutput();
}

var output = await JjUtilsJs.getLogOutput();

console.log(output);

console.log("Hello, world!");

function greet(name) {
  console.log("Hello, " + name + "!");
}

export {
  getLogOutput ,
  output ,
  greet ,
}
/* output Not a pure module */
